### ISSUE TITLE
Plugin fails in gradle 8.1 with :forkedSpringBootRun

### ISSUE THREAD

**Issue by EAlf91** [springdoc/springdoc-openapi-gradle-plugin#128] opened 2023-08-23 07:52 UTC
I found the old issue being closed but it is not resolved yet.

Quote from the old ticket:

Unfortunately, this doesn't seem to be resolved. 

Gradle version: 8.1
Plugin version: 1.7.0

This issue is still present. As some people mentioned, this workaround seems to work:
```
tasks {
  forkedSpringBootRun {
        doNotTrackState("See https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/102")
    }
}
```

_Originally posted by @pcimcioch in https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/102#issuecomment-1686337972_

same for me 

Current Setup:
```
Gradle 8.1
------------------------------------------------------------

Build time:   2023-04-12 12:07:45 UTC
Revision:     40ba32cde9d6daf2b92c39376d2758909dd6b813

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Amazon.com Inc. 17.0.7+7-LTS)
OS:           Windows 10 10.0 amd64


plugins {
    id "java"
    id "idea"
    id "org.springframework.boot" version "3.1.+"
    id "org.springdoc.openapi-gradle-plugin" version "1.7.0"
    id "io.spring.dependency-management" version "1.1.+"
    id "maven-publish"
}

The workaround did the trick for me too for now

**Comment by kkocel** [comment] 2023-08-30 09:40
For me, the workaround mentioned above did not work - I had to add dependsOn manually thanks to @rivancic
https://github.com/kkocel/openapigradlerepro/pull/1

**Comment by hosamaly** [comment] 2024-06-11 22:50
This issue looks like a duplicate of #120. There is a suggested workaround there that I used successfully.

**Comment by bnasslahsen** [comment] 2024-06-22 19:14
@EAlf91,

 #142 should fix this issue.

**Closed by bnasslahsen** 2024-06-22 19:14 UTC
